production:
    .settings:
        base:       https://mediascore.avpreserve.com
        url:        https://mediascore.avpreserve.com
 
dev:
    .settings:
        base:     http://avp.localhost/frontend_dev.php
        url:      http://avp.localhost
        base_path : checking/
        
all:
  .settings:
      contactUs:     contactus@indiana.edu
      contact:       support@indiana.edu
      
      